# Generated by Django 5.0.2 on 2024-02-25 18:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(blank=True, help_text='Дата прохождения игры пользователем', verbose_name='Дата прохождения игры')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Рейтинг игры пользователем', validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг игры')),
                ('start_date', models.DateField(blank=True, help_text='Дата начала прохождения игры пользователем', verbose_name='Дата начала прохождения игры')),
                ('end_date', models.DateField(blank=True, help_text='Дата завершения прохождения игры пользователем', verbose_name='Дата завершения прохождения игры')),
                ('progress', models.PositiveIntegerField(blank=True, help_text='Прогресс прохождения игры (в процентах)', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс прохождения игры')),
                ('game', models.ForeignKey(help_text='Связь игры пользователя с игрой', on_delete=django.db.models.deletion.CASCADE, related_name='game_gameuser', to='game.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Игра пользователя',
                'verbose_name_plural': 'Набор игр пользователей',
            },
        ),
    ]
