# Generated by Django 5.0.2 on 2024-03-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Онлайн пользователь или нет', verbose_name='Флаг наличия онлайна пользователя'),
        ),
    ]
